const timerButton = document.querySelector('#timerButton');
const ordspråkDisplay = document.querySelector('#display');
const ordspråkButton = document.querySelector("#ordspråkButton");
const winningDisplay = document.querySelector("#wDisplay");
const numberOfPlayers = JSON.parse(localStorage.myPlayers);
const winningScore = parseInt(localStorage.winningScore);
const timerDuration = parseInt(localStorage.timer);
winningDisplay.textContent = winningScore;
let isGameOver = false;
timerButton.disabled = true;

// function to dynamically add player buttons
// with the names from local storage
for (let i = 0; i < numberOfPlayers.length; i++) {
    let playerButton = document.createElement("button");
    playerButton.setAttribute("class", "playerButton");
    if (i % 2 === 0) {
        playerButton.setAttribute("class", "blueButton");
    }
    else {
        playerButton.setAttribute("class", "yellowButton");
    }
    playerButton.setAttribute("name", `${numberOfPlayers[i]}`);
    playerButton.textContent = `${numberOfPlayers[i]}, poäng: 0`;
    let parent = document.querySelector("#playerButtons");
    parent.appendChild(playerButton);
    numberOfPlayers[i] = { score: 0, button: playerButton };
    numberOfPlayers[i].button.addEventListener("click", () => {
        updateScores(numberOfPlayers[i]);
    })
    numberOfPlayers[i].button.disabled = true;
}


const array = [
    "Alla taggar utåt",
    "Alla tiders",
    "Allena saliggörande",
    "Ana argan list",
    "Ana ugglor i mossen",
    "Andra bullar",
    "Armbåga sig fram",
    "Av det rätta virket",
    "Av samma korn och skrå",
    "Av samma skrot och korn",
    "Avsked på grått papper",
    "Bakom flötet",
    "Bakom lyckta dörrar",
    "Bakom lås och bom",
    "Balansera på slak lina",
    "(Som) balsam för själen",
    "Barka åt skogen",
    "Barn av sin tid",
    "Basunera ut",
    "Be för sin sjuka mor",
    "Befinna sig i fritt fall",
    "Befinna sig i förskingringen",
    "Begära någons huvud på ett fat",
    "Behandla/ta i någon med silkesvantar",
    "Bara toppen av ett isberg/på isberget",
    "Beväpnad till tänderna",
    "Binda ris för/åt egen rygg",
    "Bita av någon",
    "Bita huvudet av skammen",
    "(Få/tvingas) bita i det sura äpplet",
    "Bita i gräset",
    "Bjuda med armbågen",
    "Bjuda till",
    "Black om foten",
    "Blek kopia",
    "Bli blåst/snuvad/lurad på konfekten",
    "Bli vid sin läst",
    "Blod på händerna",
    "Blommor och bin",
    "Blåsa faran över",
    "Bollen är rund",
    "Brinna för något",
    "Brinner i knutarna",
    "Bränna sina broar",
    "Bränna sina skepp",
    "Bränna sitt ljus i båda ändar",
    "Bröd och skådespel",
    "Bulla upp",
    "Bygger bo i huvudet",
    "Bygga broar",
    "Bygga luftslott",
    "Byta fot",
    "Både ha och äta kakan / både äta kakan och ha den kvar",
    "Både hängslen och livrem",
    "Bära hundhuvudet",
    "Bära något i sitt sköte",
    "Bära syn för sägen",
    "Börja på ny kula",
    "Cirkeln är sluten",
    "Damma av något",
    "Dansa efter någons pipa",
    "Dansa på någons grav",
    "Dansen kring den gyllene kalven/guldkalven",
    "Den breda vägen",
    "Den dagen, den sorgen",
    "Den fula ankungen",
    "Den gubben går/gick inte",
    "Det blev pannkaka av alltihop",
    "Det bästa är fiende till det goda",
    "Det fina i kråksången",
    "Det flyger inga stekta sparvar i munnen på en",
    "Det går sin gilla gång",
    "Det går utför",
    "Det knallar och går",
    "Det kan du hoppa upp och sätta dig på",
    "Det kan du skriva upp",
    "Det lackar mot jul",
    "Det man inte har i huvudet får man ha i benen",
    "Det står och faller med honom/henne/den/det",
    "Det täcka könet",
    "Det vete fåglarna",
    "Ditt och datt – Lite av varje.",
    "Don efter person",
    "Dra/skära/ta alla över en/samma kam",
    "Dra/släpa benen efter sig",
    "Dra det längsta/kortaste strået",
    "Dra dit pepparn växer",
    "dra åt helvete.)",
    "Dra det tyngsta lasset",
    "Dra en lans för någon/något",
    "Dra ett streck över det som varit",
    "Dra/hålla i trådarna",
    "Dra/hålla i tåtarna",
    "Dra igång",
    "Dra ihop sig",
    "Dra/ta lärdom av något – ",
    "Dra mig baklänges",
    "Dra något gammalt över sig",
    "Dra något i långbänk",
    "Dra på munnen/smilbanden/smilbandet",
    "Dra på trissor",
    "Dra sig till minnes",
    "Dra sig tillbaka",
    "Dra sina färde",
    "Dra sin sista suck",
    "Dra sitt strå till stacken",
    "Dra timmerstockar",
    "Dra/rycka undan mattan för någon/något",
    "Dra ut på något",
    "Dra ut på tiden",
    "Dra växlar på något",
    "Dra åt svångremmen",
    "Dra öronen åt sig",
    "Dragen vid näsan",
    "Dras med något –",
    "Driva något till sin spets",
    "Droppe i havet",
    "Droppen som fick bägaren att rinna över",
    "Duka under",
    "Dummare än tåget",
    "Därom tvista de lärde",
    "Döden i grytan",
    "Dödens lammunge",
    "Efter många om och men",
    "Eftertankens kranka blekhet",
    "Ekorrhjulet, sitta fast i ekorrhjulet, ta sig ur ekorrhjulet",
    "Eld i baken",
    "Eld och lågor",
    "Elda för kråkorna",
    "Elefant i en porslinsaffär/porslinsbutik",
    "Elefanten i rummet/en elefant i rummet",
    "En annan femma",
    "En fågel har viskat/kvittrat (i mitt öra)",
    "En gång för alla",
    "En vacker dag",
    "Enligt/efter konstens alla regler",
    "Ess i rockärmen",
    "Ett horn i sidan till någon",
    "Ett hår av Hin",
    "Ett litet korn av sanning",
    "Ett ljus i mörkret",
    "Ett strå vassare",
    "Falla i god jord",
    "Falla/hamna mellan stolarna",
    "Falla någon på läppen",
    "Falla på eget grepp",
    "Fan och hans moster",
    "Fara med osanning",
    "Fara och flyga",
    "Fara å/på färde",
    "Fel ute",
    "Fatta galoppen",
    "Femte hjulet under vagnen",
    "Fin i kanten",
    "Finns det hjärterum så finns det stjärterum",
    "Fina fisken",
    "Fiska i grumligt/grumliga vatten",
    "Fjärilar i magen",
    "Fjäder i hatten",
    "Flyga i luften",
    "Flyta ovanpå",
    "Flåsa någon i nacken",
    "Frid och fröjd",
    "Fritt fram",
    "Från ax till limpa",
    "Från vettet",
    "Ful fisk",
    "Full i fan",
    "full i sjutton",
    "Full rulle",
    "Full som en alika",
    "Få betalt under bordet, få pengar under bordet –",
    "Få blodad tand",
    "Få det hett om öronen",
    "Få en släng av sleven",
    "Få en syl i vädret –",
    "Få ett kok stryk",
    "Få frispel",
    "Få för gammal ost, få igen för gammal ost, få betalt för gammal ost, ge igen för gammal ost",
    "Få fötter",
    "Få kalla fötter",
    "Få kalla handen",
    "Få kalla kårar",
    "Få nys om något",
    "Få något om bakfoten",
    "Få någon/något på halsen",
    "Få någon/något på hjärnan",
    "Få silkessnöret",
    "Få sina fiskar varma",
    "Få tji",
    "Få vatten på sin kvarn",
    "Få veta att man lever",
    "Få ändan ur vagnen",
    "Född i farstun -",
    "Född med en silversked i munnen",
    "Följa/gå i någons fotspår",
    "För allt smör i Småland",
    "För allt vad tygen håller",
    "För fulla muggar",
    "För handen",
    "För hela slanten",
    "För kung och fosterland",
    "Föra någon bakom ljuset",
    "Förstå hur landet ligger",
    "Försöka ta ner månen",
    "Förvalta sitt pund",
    "Förvrida huvudet på någon",
    "Gammal i gården,",
    "Gammal som gatan –",
    "Gamla surdegar",
    "Ge järnet",
    "Ge någon en känga",
    "Ge någon fria",
    "lösa tyglar",
    "Ge svar på tal",
    "Ge upp andan",
    "Ge vid handen (att)",
    "Gjuta olja på vågorna",
    "Glida fram/in/omkring på en räkmacka",
    "Glad som en lärka",
    "Glimten i ögat",
    "Gnugga händerna",
    "Goddag – yxskaft",
    "Gripa efter ett halmstrå",
    "Gripa/ta något ur luften",
    "Gripa tillfället i flykten",
    "Grov i munnen",
    "Ge någon gråa hår",
    "Gråta blod",
    "Grädde(n) på moset",
    "Gräva ned stridsyxan",
    "Gräva sin egen grav",
    "Gräva upp stridsyxan",
    "Gå av stapeln",
    "Gå bakom knuten",
    "Gå bakom ryggen på någon",
    "Gå bet på något",
    "Gå bort",
    "Gå dit näsan pekar",
    "Gå/skära genom märg och ben",
    "Gå i bräschen för något",
    "Gå i gamla hjulspår, fastna i gamla hjulspår",
    "Gå i graven",
    "Gå i spinn",
    "Gå i stöpet",
    "Gå i taket",
    "Gå in i väggen",
    "Gå man ur huse",
    "Gå med håven",
    "Gå någon på nerverna",
    "Gå på en mina",
    "Gå på i ullstrumporna",
    "Gå på knäna",
    "Gå på pumpen",
    "Gå till botten med något",
    "Gå till storms mot något",
    "Gå troll i något",
    "Gå under",
    "Gå under jorden",
    "Gå under klubban",
    "Gå upp ett ljus för någon",
    "Gå upp i limningen",
    "Gå ur tiden",
    "Gå åt pipan",
    "Gå åt skogen",
    "Gå över lik",
    "Gå över ån efter vatten",
    "Göra en fuga",
    "Göra en höna av en fjäder",
    "Göra någon/något rättvisa",
    "Göra ont värre",
    "Göra rent hus",
    "Göra sig själv rättvisa",
    "Göra slag i saken",
    "Göra stora ögon",
    "Göra upp räkningen",
    "Göra våld på",
    "Göra våld på sig själv",
    "Ha det väl förspänt",
    "Ha en bulle i ugnen",
    "Ha en oplockad gås med någon",
    "Ha en räv bakom örat",
    "Ha en skruv lös",
    "Ha ett finger med i leken",
    "Ha god hand med",
    "Ha gröna fingrar",
    "Ha huvudet på skaft",
    "Ha ögonen på skaft",
    "Ha/stoppa huvudet under armen",
    "Ha höga tankar om någon",
    "Ha häcken full",
    "Ha alla ...",
    "Ha alla hästar i stallet",
    "Ha alla hästar hemma",
    "Ha alla getter hemma",
    "Ha alla skruvar i behåll",
    "Ha fått sina törnar",
    "Ha is i magen",
    "Ha kläm på något",
    "Ha lite på fötterna",
    "Ha långa fingrar",
    "Ha långa öron",
    "Ha millimetrarna på sin sida",
    "Ha mycket innanför pannbenet",
    "Ha många bollar i luften",
    "Ha många järn i elden",
    "Ha många strängar på sin lyra",
    "Ha nio liv",
    "Ha något i kikaren",
    "Ha något i ryggmärgen",
    "Ha något i släptåg",
    "Ha något i bagaget",
    "Ha något på tungan",
    "Ha något/någon som i en liten ask",
    "Ha några år på nacken",
    "Ha näsan i vädret",
    "Ha pippi på något",
    "Ha på fötterna",
    "Ha rent mjöl i påsen",
    "Ha råg i ryggen",
    "Ha satt sin sista potatis",
    "Ha sett sina bästa dagar",
    "Ha sitt på det torra",
    "Ha skinn på näsan",
    "Ha spenderbyxorna på sig",
    "Ha sålt smöret och tappat pengarna",
    "Ha siktet inställt på något",
    "Ha tomtar på loftet",
    "Ha torrt på fötterna",
    "Ha (alla, många) trumf på hand",
    "Ha tumme med någon",
    "Ha tummen i ögat på någon",
    "Ha tummen mitt i handen",
    "Ha vaknat på fel sida",
    "Ha vassa armbågar",
    "Ha vind i seglen",
    "Ha änglavakt",
    "Ha ögon i nacken",
    "Ha ögonen med sig -",
    "Ha överlevt sig själv",
    "Hack i häl",
    "Haj på (något)",
    "Halka in på ett bananskal",
    "Hals över huvud",
    "Hamna i blåsväder",
    "Hamna i knipa",
    "Hamna i skymundan –",
    "Hamna på överblivna kartan",
    "Han eller hon skulle inte göra en fluga förnär",
    "Han eller hon spottar inte i glaset",
    "Handen på hjärtat ...",
    "Handla/agera på eget bevåg",
    "Handsken är kastad",
    "Har man sagt A får man säga B",
    "Har man tagit Fan i båten får man ro honom i land",
    "Har varit i säck innan det kom i påse",
    "Hatten av för",
    "Hatt på hatt",
    "Hela baletten",
    "Hela konkarongen",
    "Hellre fria än fälla",
    "Helt uppåt väggarna",
    "Herre i sitt eget hus",
    "Herre på täppan",
    "Het potatis",
    "Het på gröten",
    "Hissen går inte hela vägen upp",
    "Historien upprepar sig",
    "Hjulet snurrar men hamstern är död",
    "Hjälpa någon på traven",
    "Hjärtat i halsgropen",
    "Hjärtat på rätt ställe",
    "Hoppa i galen tunna",
    "Hoppa upp och sätta sig på något",
    "Hoppa ur skålen",
    "Hoppa över skaklarna",
    "Hosta upp pengar",
    "Hugga i sten",
    "Hugget i sten",
    "Hugget som stucket",
    "Hundra på (något)",
    "Hur man än vänder sig har man rumpan bak",
    "Huvuden kommer att rulla",
    "Hålla alla trådar i sin hand",
    "Hålla fanan högt",
    "Hålla god min (i elakt spel)",
    "Hålla grytan kokande",
    "Hålla hov",
    "Hålla hus",
    "Hålla i rodret",
    "Hålla i schack",
    "Hålla i taktpinnen",
    "Hålla låda",
    "Hålla någon kort",
    "Hålla masken",
    "Hålla någon på halster",
    "Hålla någon på sträckbänken",
    "Hålla någon på halster",
    "Hålla någon stången",
    "Hålla någon om ryggen",
    "Hålla någon under armarna",
    "Hålla skenet uppe",
    "Hålla sig i skinnet",
    "Hålla sig på mattan",
    "Hålla sig på sin kant",
    "Hålla ställningarna",
    "Hålla tand för tunga",
    "Hålla tummarna för någon/något",
    "Hålla tungan rätt i mun",
    "Hålla varandra om ryggen",
    "Hålla ångan uppe",
    "Hålla ögonen på något",
    "Hålla ögonen öppna",
    "Hårda bud i Mellerud",
    "Hälla vatten på en gås",
    "Hälsa hem",
    "Hänga ihop som ler och långhalm",
    "Hänga läpp",
    "Hänga på ...",
    "Hänga på en skör tråd",
    "Hänga på ett hår",
    "Hänga på gärsgårn",
    "Hänga ut någon",
    "Här blir inga barn gjorda",
    "Här ligger en hund begraven",
    "Härtill är jag nödd och tvungen",
    "Hög tid",
    "Högsta hönset",
    "Högt i tak",
    "Höja någon till skyarna",
    "Höja på ögonbrynen",
    "Höjt över allt tvivel",
    "Höljt i dunkel",
    "Höra från hästens mun",
    "Höra gräset gro",
    "I bara mässingen",
    "I blåsten",
    "I brådrasket",
    "Det blir inte gjort i brådrasket",
    "I de lugnaste vatten",
    "I de lugnaste vattnen simmar de största fiskarna",
    "I det blå",
    "I det närmaste",
    "I en annan värld",
    "I ett nötskal",
    "I faggorna",
    "I farten",
    "I godan ro",
    "I grevens tid",
    "I elfte timmen",
    "i sista minuten",
    "I hatten",
    "I hetluften",
    "I krokarna",
    "I kölvattnet",
    "I laga ordning",
    "I mångt och mycket",
    "I någons kläder",
    "I någons tankar",
    "I rasande fart",
    "I ropet",
    "I rätta händer",
    "I rödaste rappet",
    "I sakta mak",
    "I senaste laget",
    "I sin glans dagar",
    "I sin krafts dagar",
    "I sin linda",
    "I sina bästa år",
    "I sinom tid",
    "Tids nog.",
    "I sista minuten/i sista ögonblicket",
    "I sitt anletes svett",
    "I sitt esse",
    "I sitt rätta element",
    "I sjunde himlen",
    "I stort sett",
    "I stridens hetta",
    "I säkert förvar",
    "I tid och otid",
    "I ur och skur",
    "Icke sa Nicke",
    "Id och strid",
    "Illa kvickt",
    "In genom ena örat och ut genom andra",
    "Ingen dans på rosor",
    "Ingen fara på taket",
    "Inte gå av för hackor",
    "Ingen ko på isen",
    "Ingen ko på isen (så länge rumpan är i/på land)",
    "Inget man snyter ur näsan",
    "Inte gjort på en kafferast",
    "Inget övrigt att önska",
    "Inom lagens råmärken",
    "Inte en levande själ",
    "inte en kotte",
    "Inte ett jota",
    "Inte ett öga torrt",
    "Inte ligga sömnlös",
    "Inte mycket att hänga i julgranen",
    "Inte vara född i farstun",
    "Intet (är) nytt under solen",
    "Intresseklubben antecknar",
    "I rödaste rappet",
    "I sus och dus",
    "Jag mötte Lassie",
    "Jaga någon med blåslampa",
    "Joxa med trasan",
    "Jämföra äpplen och päron",
    "Kacka i eget bo",
    "Kaka på kaka",
    "Kalv på grönbete",
    "Kamma noll",
    "Kamma hem något",
    "Kapitalt misslyckande/Att misslyckas kapitalt",
    "Karl för sin hatt",
    "Kasta en blick",
    "Kasta ett getöga på någon/något",
    "Kasta ett öga på någon/något",
    "Kasta goda pengar efter dåliga",
    "Kasta in handduken",
    "Kasta (nytt) ljus över något",
    "Kasta loss",
    "Kasta paj, även Pajkastning",
    "Kasta pengar i sjön",
    "Kasta pärlor för svin",
    "Kasta sten i glashus",
    "Kasta ut barnet med badvattnet",
    "Kasta veven",
    "Kasta vatten",
    "Kasta yxan i sjön",
    "Katt bland hermelinerna",
    "Katt på hett plåttak",
    "Katt på hett plåttak",
    "Katten på råttan, råttan på repet ...",
    "Kattens lek med råttan",
    "Kavla upp ärmarna",
    "Kejsarens nya kläder",
    "Kila runt hörnet",
    "Kila vidare",
    "Klammeri med rättvisan",
    "Klapp på axeln",
    "Klappat och klart",
    "Klara strupen",
    "Klart och betalt",
    "Klart som korvspad",
    "Klen i anden",
    "Klen tröst",
    "Klockrent",
    "Klok som en pudel",
    "Klä sig i säck och aska",
    "Klä skott",
    "Knaka i fogarna",
    "Knalla och gå",
    "Knappt om utrymme",
    "Knyta Hymens band",
    "Knyta näven i fickan/byxfickan",
    "Knyta sig",
    "Knyta till/ihop säcken",
    "Knäpp på näsan",
    "Koka soppa på en spik",
    "Kokar ner till",
    "Kola vippen",
    "Koloss på lerfötter",
    "Komma från hjärtat",
    "Komma i bakvattnet",
    "Komma på efterkälken",
    "Komma på grön kvist",
    "Komma på kant med någon",
    "Komma på skam",
    "Komma till skott med något",
    "Komma till vägs ände –",
    "Komma undan helskinnad",
    "Komma undan med blotta förskräckelsen",
    "Komma under lupp –",
    "Komma ur askan i elden",
    "Kors i taket",
    "Kosta skjortan",
    "Kratta manegen",
    "Krossa någons hjärta",
    "Krypa till korset",
    "Kryssa mellan Skylla och Karybdis",
    "Kräla i stoftet",
    "Krösus",
    "Kunna försätta berg",
    "Kusten är klar",
    "Kyss Karlsson!",
    "Kyss mig i arslet!",
    "Kyssa sin faster/som att kyssa sin faster",
    "Känna hur vinden blåser",
    "Känna lössen på gången",
    "Känna någon på pulsen",
    "Känna sina pappenheimare",
    "Käringen mot strömmen",
    "Köpa grisen i säcken",
    "Köp inte grisen i säcken.",
    "Kör i vind!",
    "Kör så det ryker!",
    "Köra huvudet i väggen",
    "Köra någon på porten",
    "Körd i grus",
    "Körd i botten",
    "Kött på benen",
    "Lacka ur",
    "Lag och ordning",
    "Lagens (långa) arm",
    "lagens väktare",
    "Lagvrängare",
    "Lapp på luckan",
    "Larva sig",
    "Le i mjugg",
    "Leka med elden",
    "Leka rommen av sig",
    "Lengräddad",
    "Leta efter en nål i en höstack",
    "Leta efter något med ljus och lykta",
    "Leva loppan",
    "Leva på hoppet",
    "Leva som man lär",
    "Leva under knapphetens stjärna",
    "Leva ur hand i mun",
    "Lida mot sitt slut",
    "Ligga bakom",
    "Ligga för fäfot",
    "Något ligger i träda",
    "Ligga hästlängder före",
    "Ligga i",
    "Ligga illa till",
    "Ligga i lä",
    "Ligga i selen",
    "Ligga i startgroparna",
    "Ligga i stöpsleven",
    "Ligga lågt",
    "Ligga någon i fatet",
    "Ligga någon till last",
    "Ligga någon varmt om hjärtat",
    "Ligga på",
    "Ligga på sofflocket",
    "Lika goda kålsupare.",
    "Lika som bär",
    "Lite här och var",
    "Liv i luckan",
    "Livet på en pinne",
    "Ljuga sig blå",
    "Ljuga som hästar travar",
    "Ljuger så han/hon tror sig själv",
    "Ljus(et) i slutet av tunneln",
    "Lova guld och gröna skogar",
    "Lova runt och hålla tunt",
    "Lova vitt och brett",
    "Lugn i stormen",
    "Lugna puckar",
    "Luktar/smakar pyton",
    "Lusläsa",
    "Luspank",
    "Luspudel",
    "Lyckans ost",
    "Lyfta på förlåten",
    "Lyfta på hatten för",
    "Lyfta sig själv i håret",
    "Lysa med sin frånvaro",
    "Lyset är på men det är ingen hemma",
    "Lågt hängande frukt",
    "Långt från ära och redlighet",
    "Låta barn vara barn",
    "Låta bilan falla",
    "Låta maten tysta mun",
    "Låta målvakten stå i mål",
    "Låta nåd gå före rätt",
    "Låta rättvisan ha sin gång",
    "Låta udda vara jämnt",
    "Låtsas som det regnar",
    "Lägg ägg!",
    "Lägga alla ägg i samma korg",
    "Lägga benen på ryggen",
    "Lägga hämsko på något",
    "Lägga fingrarna emellan",
    "Lägga i malpåse",
    "Lägga korten på bordet",
    "Lägga kraft bakom orden",
    "Lägga lök på laxen",
    "Lägga locket på",
    "Lägga manken till",
    "Lägga ner",
    "Lägga något på hyllan",
    "Lägga något på is",
    "Lägga något på minnet",
    "Lägga näsan i blöt",
    "Lägga orden i munnen på någon",
    "Lägga på en rem",
    "Lägga på ett kol",
    "Lägga rabarber på något",
    "Lägga sig ner och dö",
    "Lägga sig under kniven",
    "Lägga sig vinn om något",
    "Lägga sista handen vid något",
    "Lägga skorna på hyllan",
    "Lägga sordin på stämningen",
    "Lägga sten på börda",
    "Lägga två strån i kors",
    "Lägga ut en snara för någon",
    "Lägga ut texten",
    "Lägga vantarna på något",
    "Lämna någon i sticket",
    "Lära någon mores",
    "Lära någon veta hut",
    "Läsa lagen för någon",
    "Läsa lusen av någon",
    "Läsa mellan raderna",
    "Lätt på foten",
    "Lögn och förbannad dikt",
    "Löpa linan ut",
    "Mala på",
    "Man mot man",
    "Man måste lära sig krypa innan man kan gå",
    "Man skall köpa till sillen och sälja till kräftorna",
    "Man skall leva för varandra",
    "Man skall så med handen, inte med fulla säcken",
    "Man tager vad man haver",
    "Mannaminne",
    "Man vet vad man har men inte vad man får",
    "Matjord i fickorna",
    "Med buller och bång",
    "Med byxorna nere",
    "Med fingrarna i kakburken/syltburken",
    "Med flaggan i topp",
    "Med flinka fingrar",
    "Med hull och hår",
    "Med mössa/-n i hand",
    "Med någons goda minne",
    "Med/Ha näsan ovanför vattenbrynet",
    "Med nöd och näppe",
    "Med på ett hörn",
    "Med på noterna",
    "Med på tåget",
    "Med sanningen överensstämmande",
    "Med varm hand",
    "Medaljens baksida",
    "Mellan fyra ögon",
    "Mellan hägg och syren",
    "Mellan skål och vägg",
    "Mellan varven",
    "Min tillkommande",
    "Missa tåget",
    "Mittåt!",
    "Moment 22",
    "Mota Olle i grind",
    "Mumla i skägget",
    "Mycket ska man höra innan öronen faller av",
    "Mycket snack och lite verkstad",
    "Mycket vatten har flutit under broarna sedan dess",
    "Mycket väsen för ingenting",
    "Much Ado About Nothing",
    "Myror i byxorna",
    "Myror i brallorna",
    "Må det bära eller brista",
    "Måla fan på väggen",
    "Måla in sig i ett hörn",
    "Många hövdingar, men få indianer",
    "Möta sitt Waterloo",
    "Mötas på halva vägen",
    "Nagel i ögat",
    "Nagelfara något",
    "Nu får du guldstjärna",
    "Nu gick det upp ett ljus",
    "Nu går skam på torra land",
    "Nu trillade polletten ner",
    "Nu är det klippt",
    "Nu är det kokta fläsket stekt",
    "Nu är det kört",
    "Nu är goda råd dyra",
    "Nu är jag ute på okänt vatten",
    "Nu är måttet rågat",
    "Någonting är ruttet",
    "Något har sett/ser dagens ljus",
    "Något i hästväg",
    "Något som katten släpat in",
    "När andan faller på",
    "När det kommer till kritan",
    "När krubban är tom bits hästarna",
    "När skoputsarna frågar om aktietips är det dags att sälja",
    "När Adam var länsman",
    "När man talar om trollen så står de i farstun",
    "Nära en orm vid sin barm",
    "Nära och kära",
    "Nära ögat",
    "Närma sig med stormsteg",
    "Nästa år i Jerusalem",
    "Nöt att knäcka",
    "Och hör sen",
    "Odla sin kål",
    "Om inte om hade funnits",
    "Om sig och kring sig",
    "Ond cirkel",
    "Ord står mot ord",
    "Ord och inga visor",
    "Ordning och reda, pengar på freda'",
    "Ormens väg på hälleberget",
    "Osa katt",
    "Osa svavel",
    "Oskrivet blad",
    "Osvuret är bäst",
    "Pang på rödbetan",
    "Peka med hela handen",
    "Pengar luktar inte",
    "Pecunia non olet",
    "Peppar, peppar, ta i trä",
    "Pest eller kolera",
    "Pigg som en mört – Vara mycket alert, kvick och vaken.",
    "Plattan i mattan",
    "Plocka russinen ur kakan",
    "Polsk riksdag",
    "Pompa och ståt",
    "Praktiskt taget",
    "Prata bredvid mun",
    "Prata goja",
    "Prata i nattmössan",
    "Prata i vädret",
    "Prata i munnen på varandra",
    "Prata smörja",
    "Pricken över i:et.",
    "Pudelns kärna",
    "På alla fyra",
    "På allas läppar",
    "På bar backe",
    "På den säkra sidan",
    "På det hela taget",
    "På efterkälken",
    "På en höft",
    "På ett bräde",
    "På fallrepet",
    "På fem röda",
    "På fri fot",
    "På G",
    "På glid -",
    "På gräsrotsnivå",
    "På hugget",
    "På bettet",
    "På håret",
    "På kanelen",
    "På kornet",
    "På krigsstigen",
    "På löpande band",
    "På lösa boliner",
    "På måfå",
    "På papperet",
    "På pin kiv",
    "På pricken",
    "På rak arm",
    "På resande fot",
    "På rätt köl, på rät köl",
    "På samma våglängd",
    "På sandlådenivå",
    "På sin mammas gata",
    "På sin höjd",
    "På sin vakt",
    "På smällen",
    "På språng",
    "På stående fot",
    "På tapeten",
    "På tu man hand",
    "På upphällningen",
    "På vid gavel",
    "På vift",
    "På vippen",
    "Rak i ryggen/rakryggad",
    "Rammelbuljong",
    "Raska gossar",
    "Regnet står som spön i backen",
    "Rena rama ...",
    "Rent ryskt",
    "Resa ragg/borst",
    "Resa sig som fågel Fenix ur askan",
    "Resa sig som på ett givet tecken",
    "Reta gallfeber på någon",
    "Rida ut en storm",
    "Rim och reson",
    "Rimmar illa",
    "Rinna ut i sanden",
    "Ris och ros",
    "Rubb och stubb",
    "Rulla hatt",
    "Rulla på",
    "Rulla tummarna",
    "Rund under fötterna",
    "Rycka upp sig",
    "Rymma fältet",
    "Råda bot på något",
    "Råka i luven på varandra",
    "Råttorna lämnar ett sjunkande skepp",
    "Räfst och rättarting",
    "Ränderna går aldrig ur",
    "Rätt skall vara rätt",
    "Rätt och riktigt",
    "Rätta mun(nen) efter matsäcken",
    "Röd tråd",
    "Röra runt/om i grytan",
    "Röra upp himmel och jord",
    "Rösta med fötterna",
    "Rött skynke",
    "Rött öre",
    "Sagt och gjort",
    "Saken är biff",
    "Sakta i backarna",
    "Sakta men säkert",
    "Salig röra",
    "Samla i ladorna",
    "Sanningens minut",
    "Sans och balans",
    "Satsa på fel häst",
    "Se färg torka",
    "Se ljuset i tunneln",
    "Se längre än näsan räcker",
    "Se med blida ögon på",
    "Se mellan fingrarna",
    "Se om sitt hus",
    "Se spöken mitt på ljusa dagen",
    "Se röken av",
    "Se rött",
    "Se sanningen i vitögat",
    "Se sig i månen efter något",
    "Se skogen för alla träd",
    "Se ut som sju svåra år",
    "Sedan dess har det flutit mycket vatten under broarna",
    "Sedan Eldkvarn brann",
    "Sent omsider",
    "Sent ska syndarna vakna",
    "Serverat som på silverfat",
    "Sig själv närmast",
    "Sila mygg och svälja kameler",
    "Simma med/mot strömmen",
    "Sin beskärda del",
    "Sin egen lyckas smed",
    "Sin glans dagar",
    "Sist men inte minst",
    "Sista spiken i kistan",
    "Siste man på skansen",
    "Sitta hemma och uggla",
    "Sitta hårt åt",
    "Sitta i klistret",
    "Sitta i knät på någon",
    "Sitta i orubbat bo",
    "Själv hade Mussolini kunnat sitta kvar i orubbat bo, och antagligen gått till historien som...",
    "Sitta i samma båt",
    "Sitta i väggarna",
    "Sitta inne",
    "Sitta och häcka",
    "Sitta och mögla",
    "Sitta/vara (uppe) i smöret",
    "Sitta på pottkanten",
    "Sitta på sina höga hästar",
    "Sitta på två stolar samtidigt",
    "Sitta still i båten",
    "Sitta säkert i sadeln",
    "Sju sorger och åtta bedrövelser",
    "Sju svåra år",
    "Sjunga på sista versen",
    "Skaka galler",
    "Skaka något ur ärmen",
    "Skam till sägandes",
    "Skapelsens krona",
    "Skarp penna/vass penna",
    "Skarpaste/vassaste kniven i lådan",
    "Skarpt läge",
    "Ske med någons goda minne",
    "Skelett i garderoben",
    "Skepp utan roder",
    "Skilja agnarna från vetet",
    "Skinn på näsan",
    "Skita i det blå skåpet",
    "Skitprat",
    "Skjuta mygg med kanoner",
    "Skjuta sig själv i foten",
    "Sko sig (på någon)",
    "Skratta hela vägen till banken",
    "Skrida till verket",
    "Skrika/sjunga för full hals",
    "Skrika i högan sky",
    "Skriva någon på näsan",
    "Skriva under på något",
    "Skrivet i stjärnorna",
    "Skräckblandad förtjusning",
    "Skräda orden",
    "att inte skräda orden",
    "Skynda långsamt",
    "Skänk från ovan",
    "Skära pipor i vassen",
    "Skåda inte en given häst i munnen",
    "Skämmas ögonen ur sig",
    "Skörda sina frukter",
    "Skörda offer",
    "Slag i luften",
    "Slag under bältet",
    "Slaven på triumfvagnen",
    "Slicka någon i arslet/röven",
    "Slira på sanningen",
    "Slit den med hälsan!",
    "Slita hund",
    "Slita ont",
    "Sluta leden",
    "Slå blå dunster i ögonen på någon",
    "Slå dank",
    "Slå dig/er i backen på",
    "Slå dövörat till",
    "Slå en sjua",
    "Slå en parabel",
    "Slå ett slag för något",
    "Slå huvudet på spiken",
    "Slå i taket",
    "Slå in öppna dörrar",
    "Slå klackarna i taket",
    "Slå knut på sig själv",
    "Slå lock för öronen",
    "Slå mynt av något",
    "Slå ner sina bopålar",
    "Slå någon gul och blå",
    "Slå någon/något sönder och samman",
    "Slå näven i bordet",
    "Slå på stora trumman",
    "Slå på stort",
    "Slå sig för bröstet",
    "Slå sig i slang med",
    "Slå (något) sönder och samman",
    "Slå sina påsar ihop",
    "Slå två flugor i en smäll",
    "Slå vakt om något",
    "Slå vantarna i bordet",
    "Slås av något",
    "Släkten är värst",
    "Släta över något",
    "Smaka stövelklacken",
    "Smakar det så kostar det",
    "Smida medan järnet är varmt",
    "Sminka grisen",
    "Smockan hänger i luften",
    "Smolk i glädjebägaren",
    "Smäll på fingrarna",
    "Smörja kråset",
    "Smörklick på het potatis",
    "Sol ute, sol inne. Sol i hjärta, sol i sinne",
    "Sola sig i sin egen glans",
    "Som ett torrt skinn",
    "Som fan läser Bibeln",
    "Som klippt och skuren för något",
    "Sopa golvet med någon",
    "Sopa problemet under mattan",
    "Sopa rent framför/för sin egen dörr",
    "Sova på saken",
    "Spara på krutet/spara inte på krutet",
    "Sparv i tranedansen",
    "Spel för galleriet/gallerierna",
    "Spel bakom kulisserna",
    "Spela Allan",
    "Spela andrafiolen",
    "Spela ett högt spel –",
    "Spela i samma division",
    "Spela sina kort väl",
    "Spela under täcket med någon",
    "Spetsa öronen",
    "Spindeln i nätet",
    "Spotta i nävarna",
    "Sprids som askan för vinden",
    "Springande punkten",
    "Spritt språngandes naken",
    "Spänna bågen för högt",
    "Stadd vid kassa",
    "Stick i stäv mot",
    "Sticka huvudet i sanden",
    "Sticka i ögonen",
    "Sticka under stol med",
    "Sticka ut hakan",
    "Stiga åt huvudet",
    "Stirra sig blind på något",
    "Stolt som en tupp",
    "Storm i ett vattenglas",
    "Strama tyglar",
    "Streck i räkningen",
    "Strid på kniven",
    "Strida om påvens skägg",
    "Stryka med",
    "Stryka någon medhårs",
    "Stryka på foten/fötterna",
    "Sträcka vapen",
    "Strö pärlor för svinen",
    "Strö salt i såren",
    "Styv i korken",
    "Styv i nacken/styvnackad",
    "Stå för fiolerna",
    "Stå handfallen",
    "Stå i ljusan låga",
    "Stå i rampljuset",
    "Stå i skottgluggen",
    "Stå i valet och kvalet",
    "Stå inför skranket",
    "Stå/sitta med armarna i kors",
    "Stå med båda fötterna på jorden",
    "Stå med mössan i näven",
    "Stå med skägget i brevlådan/Hamna med skägget i brevlådan",
    "Stå med två tomma händer/vara tomhänt",
    "Stå med tvättad hals",
    "Stå och väga",
    "Stå pall för något",
    "Stå på egna ben",
    "Stå på god fot med någon",
    "Stå på näsan",
    "Stå på spel",
    "Stå på sig",
    "Stå på öronen",
    "Stå sitt kast",
    "Stå som fallen från skyarna",
    "Stå (någon) upp i halsen",
    "Stå vid skampålen",
    "Stånga hornen av sig",
    "Stånga sig blodig",
    "Ställa någon mot väggen",
    "Ställa sig i skamvrån",
    "Ställa till svars",
    "Ställas i dålig dager",
    "Stämma i bäcken",
    "Stöpt i samma form",
    "Störst och värst i hela Bofors",
    "Stöta och blöta något",
    "Stöta på patrull",
    "Stötesten",
    "Stötts och blötts",
    "Suga på karamellen",
    "Suga på ramarna",
    "Summa summarum",
    "Surfa på nätet",
    "Surrad vid masten",
    "Svagaste länken i kedjan",
    "Svansen mellan benen",
    "Svarta fåret",
    "Svarte Petter",
    "Svinhugg går igen",
    "Svida i skinnet",
    "Svårfjällad fisk",
    "Svälja det beska pillret",
    "Svära i kyrkan",
    "Sväva i ovisshet",
    "Sväva mellan liv och död",
    "Sväva på moln",
    "Sväva på målet",
    "Sväva på rosa moln",
    "Syna i sömmarna",
    "Synd på så rara ärtor",
    "Synda på nåden",
    "Så gott som",
    "Så in i Norden",
    "Så in i vassen",
    "Så nära sanningen man kan komma",
    "Så sant som det är sagt",
    "Så split",
    "Så sin vildhavre",
    "Så ska en slipsten dras",
    "Så tyst att man kan höra en knappnål falla",
    "Sålt smöret och tappat pengarna",
    "Såga någon/något vid fotknölarna",
    "Sånt är livet",
    "Såsom i en spegel",
    "Säga ifrån/till på skarpen",
    "Säga flaska",
    "Säker i sadeln",
    "Säker på sin sak",
    "Säkert som amen i kyrkan",
    "Som ett brev på posten",
    "Sätta bocken till trädgårdsmästare",
    "Sätta en rova",
    "Sätta fingret på något –",
    "Sätta in nådastöten",
    "Sätta käppar i hjulet",
    "Sätta livet till",
    "Sätta munkavle på någon",
    "Sätta myror i huvudet på någon",
    "Sätta ner foten",
    "Sätta någon på det hala",
    "Sätta någon på piedestal",
    "Sätta någon på plats",
    "Sätta någon på pottan/pottkanten",
    "Sätta något på kartan",
    "Sätta något på spel",
    "Sätta något under lupp",
    "Sätta p för något",
    "Sätta punkt för något",
    "Sätta sig på bakhasorna",
    "Sätta sig på höga hästar",
    "Sätta sig på tvären",
    "Sätta sitt ljus under skäppan",
    "Sätta sprätt på pengarna",
    "Sätta till alla klutar",
    "Sätta värde på något",
    "Söndra och härska",
    "Ta bladet från munnen",
    "Ta (den) bollen/pucken",
    "Ta den i tvåan",
    "Ta det kallt",
    "Ta det lite pö om pö",
    "Ta det långa benet före",
    "Ta det med en klackspark",
    "Ta det med ro",
    "Ta det piano",
    "Ta det säkra före det osäkra",
    "Ta det säkra för det osäkra",
    "Ta det vackert",
    "Ta en i det andra benet också",
    "Ta en kula för någon",
    "Ta en ände med förskräckelse",
    "Ta för sig",
    "Ta för stora ord i sin mun",
    "Ta gift på något",
    "Ta hus i helsike/helvete",
    "Ta höjd för något",
    "Ta i med hårdhandskarna",
    "Ta i med silkesvantarna",
    "Ta i så man spricker",
    "Ta igen på gungorna vad man förlorat på karusellen",
    "Ta korn på",
    "Ta kål på något",
    "Ta musten ur någon/något",
    "Ta ner månen",
    "Ta ner skylten",
    "Ta någon i hampan",
    "Ta någon i örat",
    "Ta något med en nypa salt",
    "Ta något för givet",
    "Ta någon på orden",
    "Ta på kornet",
    "Ta saken i egna händer",
    "Ta seden dit man kommer",
    "Ta sig en funderare",
    "Ta sig en styrketår",
    "Ta sig för stora friheter",
    "Ta sig (själv) i kragen",
    "Ta sig vatten över huvudet",
    "Ta sin Mats ur skolan",
    "Ta sitt förnuft till fånga",
    "Ta skeden i vacker hand",
    "Ta skruv",
    "Ta steget fullt ut",
    "Ta tempen",
    "Ta till storsläggan",
    "Ta tjuren vid hornen",
    "Tacka sin lyckliga stjärna",
    "Tagen på sängen",
    "Tala ett annat språk",
    "Tala för döva öron",
    "Tala klarspråk",
    "Tala med bönder på bönders vis och med de lärde på latin",
    "Tala med kluven tunga",
    "Tala till punkt",
    "Tala ur skägget",
    "Tappa ansiktet",
    "Tappa greppet",
    "Tappa hakan",
    "Tappa huvudet",
    "Tappa koncepten",
    "Tappa målföret",
    "Tappad bakom en vagn",
    "Tiden har runnit ut",
    "Tidens tand",
    "Tids nog",
    "Till det yttersta",
    "Till råga på allt",
    "Till sista andetaget",
    "Till syvende och sist",
    "Til syvende og sidst",
    "Till yttermera visso",
    "Tillbaka på ruta ett",
    "Timglaset är fullt",
    "Titta för djupt i glaset/titta djupt i flaskan",
    "Titta snett på någon",
    "Tomma ord",
    "Tomt i ladan",
    "Topp tunnor rasande",
    "Toppa laget",
    "Torr bakom öronen",
    "Trampa i klaveret",
    "Trampa på en öm tå",
    "Trampa spiken i botten",
    "Trampa vatten",
    "Tredje gången gillt",
    "Tretton på dussinet",
    "Trilla av pinn",
    "Trolla med knäna",
    "Tror, det gör man i kyrkan",
    "Trycka ner i skoskaften",
    "Trångt om saligheten",
    "Träffa den rätta/rätte",
    "Tröst för tigerhjärtan",
    "Tulipanaros",
    "Tummen i ögat",
    "Tu tal om något",
    "Tupp i halsen",
    "Tvätta pengar",
    "Tvätta sin smutsiga byk",
    "Tycka skjortan är trång",
    "Tystnaden talar för sig själv",
    "Två sidor av samma mynt",
    "Två sina händer",
    "Tår på tand",
    "Tårta på tårta",
    "Tända på alla fyra",
    "Tända på alla cylindrar",
    "Tälja guld med pennkniv",
    "Tälja guld med täljkniv.",
    "Tända på alla cylindrar",
    "Tänk först och tala sen",
    "Tänka på refrängen",
    "Täppa till munnen på någon",
    "Tärningen är kastad",
    "Tömma den bittra kalken",
    "Ulv/varg i fårakläder",
    "Undantaget som bekräftar regeln",
    "Under isen",
    "Under uppsegling",
    "Underbart är kort",
    "Upp på koturnen",
    "Uppe med tuppen",
    "Uppfinna hjulet på nytt",
    "Ur askan i elden",
    "Ur fas",
    "Ur gängorna",
    "Ur led är tiden",
    "Ur spel",
    "Utan att darra på manschetten",
    "Utan en tråd på kroppen",
    "Utan mål och mening",
    "Utan ände",
    "Ute efter något",
    "Ute i kylan",
    "Ute i ogjort väder",
    "Ute och cykla",
    "Ute på djupt vatten",
    "Ute på hal is",
    "Utom sig (av vrede/ilska/sorg/oro)",
    "Vacker tass",
    "Vad gäspar skårpan?",
    "Vad övrigt är, är tystnad",
    "Vakta sin tunga",
    "Var och en blir salig på sin tro",
    "Vara den som är den",
    "Vara du och bror med någon",
    "Vara igång",
    "Vara grönt",
    "Vara sig själv nog",
    "Varför är allt en trasa?",
    "Varje moln har en silverkant",
    "Varken bu eller bä",
    "Varken hackat eller malet",
    "Varm i kläderna",
    "Varm om hjärtat",
    "Vass tunga",
    "Verkligheten överträffar (ofta) dikten",
    "Veta hur en slipsten ska dras",
    "Veta hut",
    "Veta vad klockan är slagen",
    "Veta var skon klämmer",
    "Vi är alla olika i Herrens hage",
    "Vid sina sinnens fulla bruk",
    "Vid sunda vätskor",
    "Vila på hanen",
    "Vila på sina/gamla lagrar",
    "Vilja sjunka genom jorden",
    "Vind för våg",
    "Visa framfötterna",
    "Visa sig från sin goda sida",
    "Visa sig på styva linan",
    "Visa tänderna",
    "Visa var skåpet ska stå",
    "Vit lögn",
    "Vit vecka",
    "Väcka ont blod",
    "Vädra morgonluft",
    "Väga sina ord på guldvåg",
    "Väggarna har öron",
    "Välsmort munläder",
    "Vältra sig i pengar",
    "Vända andra kinden till",
    "Vända blad",
    "Vända kappan efter vinden",
    "Vända på klacken",
    "Vända på kuttingen",
    "Vända på slantarna",
    "Vända på steken",
    "Vända på varje sten",
    "Väntans tider",
    "Värdshus förb",
    "Värt papperet det är skrivet på",
    "Vässa sina knivar",
    "Växa så det knakar",
    "Yr i bollen",
    "Yr i mössan",
    "Åka på en blåsning",
    "Återfå fattningen",
    "Återgå/hänvisa till sina rötter",
    "Åt fanders",
    "Åt pipsvängen",
    "Äkta hälft",
    "Ända in i Hälsingland",
    "Ända in i kaklet",
    "Ända ut i fingerspetsarna",
    "Äpplet faller inte långt från trädet",
    "Ära den som äras bör",
    "Äta någon ur hus och hem",
    "Äta någon ur huset",
    "Äta upp vad man sagt eller gjort",
    "Äter allt, tycker mycket om barn",
    "Även du (min) Brutus?",
    "Öga för öga, tand för tand",
    "Öppna korpgluggarna",
    "Över min döda kropp",
    "Överlevt sig själv"
]

    ;


ordspråkButton.addEventListener('click', function () {
    ordspråk();
})

timerButton.addEventListener('click', function () {
    startTimer();
})

let interval = null;

function startTimer() {
    timerButton.disabled = true;
    for (let i = 0; i < numberOfPlayers.length; i++) {
        numberOfPlayers[i].button.disabled = false;
    }
    let timer = timerDuration, minutes, seconds;
    interval = setInterval(function () {
        minutes = parseInt(timer / 60, 10);
        seconds = parseInt(timer % 60, 10);

        minutes = minutes < 10 ? "0" + minutes : minutes;
        seconds = seconds < 10 ? "0" + seconds : seconds;

        ordspråkDisplay.textContent = minutes + ":" + seconds;
        if (timer === 0) {
            clearTimer(interval);
        }
        else
            timer--;
    }, 1000);
}

function clearTimer(interval) {
    ordspråkDisplay.textContent = "Skicka telefonen till nästa person.";
    clearInterval(interval);
    ordspråkButton.disabled = false;
}

function ordspråk() {
    ordspråkDisplay.textContent =
        array[Math.floor(Math.random() * array.length)];
    ordspråkButton.disabled = true;
    timerButton.disabled = false;
}

function updateScores(player) {
    if (!isGameOver) {
        player.score++;
        if (player.score === winningScore) {
            isGameOver = true;
            player.button.textContent = `${player.button.name} poäng: ${player.score}`;
            localStorage.winner = player.button.name;
            location.href = "win.html";
        }

    }
    player.button.textContent = `${player.button.name} poäng: ${player.score}`;
    ordspråkButton.disabled = false;
    clearTimer(interval);
    for (let i = 0; i < numberOfPlayers.length; i++) {
        numberOfPlayers[i].button.disabled = true;
    }
}



